# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'smart_control_hub.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SmartControlHub(object):
    def setupUi(self, SmartControlHub):
        SmartControlHub.setObjectName("SmartControlHub")
        SmartControlHub.resize(900, 550)
        SmartControlHub.setStyleSheet("QMainWindow {\n"
"    background-color: #2d2d2d;\n"
"    color: white;\n"
"}\n"
"QPushButton {\n"
"    background-color: blue;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"}\n"
"QPushButton:active {\n"
"    background-color: orange;\n"
"}\n"
"QLabel#speakerIcon {\n"
"    background-color: blue;\n"
"    border-radius: 50%;\n"
"    padding: 10px;\n"
"}\n"
"QFrame#mapsFrame {\n"
"    background-color: #f0f0f0;\n"
"    border: 1px solid #ccc;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(SmartControlHub)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftPanel = QtWidgets.QFrame(self.centralwidget)
        self.leftPanel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftPanel.setObjectName("leftPanel")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.leftPanel)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dateTimeFrame = QtWidgets.QFrame(self.leftPanel)
        self.dateTimeFrame.setObjectName("dateTimeFrame")
        self.dateTimeLayout = QtWidgets.QHBoxLayout(self.dateTimeFrame)
        self.dateTimeLayout.setObjectName("dateTimeLayout")
        self.dateLabel = QtWidgets.QLabel(self.dateTimeFrame)
        self.dateLabel.setObjectName("dateLabel")
        self.dateTimeLayout.addWidget(self.dateLabel)
        self.dayLabel = QtWidgets.QLabel(self.dateTimeFrame)
        self.dayLabel.setObjectName("dayLabel")
        self.dateTimeLayout.addWidget(self.dayLabel)
        self.verticalLayout.addWidget(self.dateTimeFrame)
        self.voiceControlFrame = QtWidgets.QFrame(self.leftPanel)
        self.voiceControlFrame.setObjectName("voiceControlFrame")
        self.voiceLayout = QtWidgets.QVBoxLayout(self.voiceControlFrame)
        self.voiceLayout.setObjectName("voiceLayout")
        self.micButton = QtWidgets.QPushButton(self.voiceControlFrame)
        self.micButton.setMinimumSize(QtCore.QSize(0, 64))
        self.micButton.setObjectName("micButton")
        self.voiceLayout.addWidget(self.micButton)
        self.verticalLayout.addWidget(self.voiceControlFrame)
        self.controlButtonsFrame = QtWidgets.QFrame(self.leftPanel)
        self.controlButtonsFrame.setObjectName("controlButtonsFrame")
        self.controlButtonsLayout = QtWidgets.QGridLayout(self.controlButtonsFrame)
        self.controlButtonsLayout.setObjectName("controlButtonsLayout")
        self.lightsOnButton = QtWidgets.QPushButton(self.controlButtonsFrame)
        self.lightsOnButton.setObjectName("lightsOnButton")
        self.controlButtonsLayout.addWidget(self.lightsOnButton, 0, 0, 1, 1)
        self.gpsOnButton = QtWidgets.QPushButton(self.controlButtonsFrame)
        self.gpsOnButton.setObjectName("gpsOnButton")
        self.controlButtonsLayout.addWidget(self.gpsOnButton, 0, 1, 1, 1)
        self.lightsOffButton = QtWidgets.QPushButton(self.controlButtonsFrame)
        self.lightsOffButton.setObjectName("lightsOffButton")
        self.controlButtonsLayout.addWidget(self.lightsOffButton, 1, 0, 1, 1)
        self.gpsOffButton = QtWidgets.QPushButton(self.controlButtonsFrame)
        self.gpsOffButton.setObjectName("gpsOffButton")
        self.controlButtonsLayout.addWidget(self.gpsOffButton, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.controlButtonsFrame)
        self.horizontalLayout.addWidget(self.leftPanel)
        self.mapsFrame = QtWidgets.QFrame(self.centralwidget)
        self.mapsFrame.setMinimumSize(QtCore.QSize(400, 0))
        self.mapsFrame.setObjectName("mapsFrame")
        self.mapsLayout = QtWidgets.QVBoxLayout(self.mapsFrame)
        self.mapsLayout.setObjectName("mapsLayout")
        self.horizontalLayout.addWidget(self.mapsFrame)
        SmartControlHub.setCentralWidget(self.centralwidget)

        self.retranslateUi(SmartControlHub)
        QtCore.QMetaObject.connectSlotsByName(SmartControlHub)

    def retranslateUi(self, SmartControlHub):
        _translate = QtCore.QCoreApplication.translate
        SmartControlHub.setWindowTitle(_translate("SmartControlHub", "Smart Control Hub"))
        self.dateLabel.setText(_translate("SmartControlHub", "Date:"))
        self.dayLabel.setText(_translate("SmartControlHub", "Day:"))
        self.micButton.setStyleSheet(_translate("SmartControlHub", "\n"
"              QPushButton#micButton {\n"
"                  background-color: #3498db;\n"
"                  border-radius: 32px;\n"
"              }\n"
"              QPushButton#micButton:hover {\n"
"                  background-color: #ff9933;\n"
"              }\n"
"             "))
        self.lightsOnButton.setText(_translate("SmartControlHub", "Lights On"))
        self.gpsOnButton.setText(_translate("SmartControlHub", "GPS On"))
        self.lightsOffButton.setText(_translate("SmartControlHub", "Lights Off"))
        self.gpsOffButton.setText(_translate("SmartControlHub", "GPS Off"))
        self.mapsFrame.setStyleSheet(_translate("SmartControlHub", "\n"
"        QFrame#mapsFrame {\n"
"            background-color: white;\n"
"            border-radius: 10px;\n"
"        }\n"
"       "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SmartControlHub = QtWidgets.QMainWindow()
    ui = Ui_SmartControlHub()
    ui.setupUi(SmartControlHub)
    SmartControlHub.show()
    sys.exit(app.exec_())
